services:
  react-dev:
    build:
      context: .
      dockerfile: react-container/Dockerfile
    image: test-react-dev:latest
    container_name: test-react-dev
    working_dir: /react-container
    volumes:
      - ./react-container:/react-container
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    command: ["/react-container/start_react.sh"]

  java-dev:
    build:
      context: .
      dockerfile: java-container/Dockerfile
    image: test-java-dev:latest
    container_name: test-java-dev
    working_dir: /java-container
    volumes:
      - ./java-container:/java-container
    stdin_open: true
    tty: true
    command: ["/java-container/start_java.sh"]

